### ISSUE TITLE
CompileError: AsyncCompile: Wasm decoding failed

### ISSUE THREAD

**Issue by o-smirnov** [gijzelaerr/js9notebook#4]
This only happens when loading via Jupyter. My cell contains this piece of code:

```
%%html
<iframe src="/files/.radiopadre/js9/js9.html" width=800 height=750></iframe>
```

In this case, ``.radiopadre/js9/js9.html`` is the local install of JS9, which Jupyter serves up as ``/files/.radiopadre/js9/js9.html``. 

I get this in the JS console:

```
astroemw.js:4 failed to asynchronously prepare wasm: CompileError: AsyncCompile: Wasm decoding failed: expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
(anonymous) @ astroemw.js:4
Promise.catch (async)
instantiateArrayBuffer @ astroemw.js:4
doNativeWasm @ astroemw.js:4
Module.asm @ astroemw.js:4
(anonymous) @ astroemw.js:4
astroemw.js:4 CompileError: AsyncCompile: Wasm decoding failed: expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
astroemw.js:4 CompileError: AsyncCompile: Wasm decoding failed: expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
abort @ astroemw.js:4
(anonymous) @ astroemw.js:4
Promise.catch (async)
instantiateArrayBuffer @ astroemw.js:4
doNativeWasm @ astroemw.js:4
Module.asm @ astroemw.js:4
(anonymous) @ astroemw.js:4
js9.html:1 Uncaught (in promise) abort({}). Build with -s ASSERTIONS=1 for more info.
```

Loading up JS9 from the same install via SimpleWebServer works fine. (And I suspect that when @ericmandel successfully displayed JS9 with an iframe [as reported here](
https://github.com/gijzelaerr/js9notebook/issues/2#issuecomment-402285357), links like ``http://localhost/~eric/index.html`` were served up by his local webserver, rather than Jupyter.)

So the workaround is to run a separate web server to serve up JS9 pages inside Jupyter cells. For proper integration though, we ned to figure out how to get everything served through Jupyter.

**Comment by ericmandel** [comment]
I don't know what it means to serve pages through Jupyter, so I don't know if I am doing that or not. Can you tell me how to do it? Right now I am in miniconda and I just do this:
````
jupyter notebook
````
It looks like it is using a server on port 8888, but again, I don't know what I am looking at.

That said, this certainly looks like a problem with support for wasm. For testing, you should turn off wasm support at the js9prefs.js level. But to do this, you'll also have to make sure that the helper support is also turned off (or we'll get into the old problems). So you need to load the js9prefs.js after adding these lines:
````
    "helperType": "none,
    "useWasm": false
````
This will skip the helper (default is to try to connect) and use asm.js instead of wasm.

If this works, I can turn off wasm for all Jupyter instances ... unless the Emsripten/wasm developers have a different idea.

**Comment by o-smirnov** [comment]
> I don't know what it means to serve pages through Jupyter, so I don't know if I am doing that or not. Can you tell me how to do it?

As I understand it, Jupyter includes a Tornado web server. When you run ``jupyter notebook`` (let's say in ``~eric``), it starts up a Tornado instance that listens on port 8888, and (by default) opens a browser window pointing to localhost:8888. So from that point on your browser talks to the Tornado server, which serves up notebooks, etc. If a notebook cell contains an iframe with source ``http://localhost:8888/files/index.html``, you're asking Tornado to give you ``~eric/index.html``. I'm guessing if you do that, you'll reproduce my problem.

**Comment by ericmandel** [comment]
Great, let me look into this. Probably there will be an update to JS9 to turn off wasm soon!

**Comment by o-smirnov** [comment]
> This will skip the helper (default is to try to connect) and use asm.js instead of wasm.

Confirmed, this works. In fact now I don't even need an iframe, I can directly load JS9 into a cell, and use JS9.Load(), and get a functioning display. There's still some crud on the JS console, I don't know if it matters:

```
jquery.min.js:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
VM510:3058 Uncaught TypeError: Cannot read property 'mouse' of undefined
    at eval (eval at globalEval (jquery.min.js:2), <anonymous>:3058:25)
    at eval (eval at globalEval (jquery.min.js:2), <anonymous>:3217:3)
    at eval (<anonymous>)
    at Function.globalEval (jquery.min.js:2)
    at text script (jquery.min.js:4)
    at Ab (jquery.min.js:4)
    at z (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
    at XMLHttpRequest.send (<anonymous>:1:781)
    at Object.send (jquery.min.js:4)
VM510:18 jQuery.Deferred exception: $(...).draggable is not a function TypeError: $(...).draggable is not a function
    at HTMLDocument.eval (eval at globalEval (http://localhost:11004/static/notebook/js/main.min.js?v=1b02566…:2:2640), <anonymous>:2:31)
    at j (eval at globalEval (http://localhost:11004/static/notebook/js/main.min.js?v=1b02566…:2:2640), <anonymous>:18:29999)
    at k (eval at globalEval (http://localhost:11004/static/notebook/js/main.min.js?v=1b02566…:2:2640), <anonymous>:18:30313) undefined
VM510:18 Uncaught TypeError: $(...).draggable is not a function
    at HTMLDocument.eval (eval at globalEval (jquery.min.js:2), <anonymous>:2:31)
    at j (eval at globalEval (jquery.min.js:2), <anonymous>:18:29999)
    at k (eval at globalEval (jquery.min.js:2), <anonymous>:18:30313)
```﻿
￼
​

**Comment by o-smirnov** [comment]
Clearly was caused by #7.
